Assets/CharacterPhysMat.physicsMaterial2D, Assets/CharacterPhysMat.physicsMaterial2D.meta, Assets/Characters.meta, Assets/Characters/Player.meta, Assets/MovementController.cs, Assets/MovementController.cs.meta, Assets/scene1.unity, ProjectSettings/InputManager.asset, ProjectSettings/Physics2DSettings.asset, ProjectSettings/QualitySettings.asset, ProjectSettings/UnityConnectSettings.asset
The player can move, jump and crouch with WASD.  No animations yet, just mechanics.  Can't jump while not grounded. Can't move while ccrouching and grounded.
=> basic WASD player movement

Assets/DestructiblePlatform.cs, Assets/DestructiblePlatform.cs.meta, Assets/MovingPlatform.cs, Assets/MovingPlatform.cs.meta, Assets/testPlatforms.unity, Assets/testPlatforms.unity.meta
I added the moving platform scripts and the destructible platform scripts. The destructible platform script may need some editing, but right now, if a player lands on it 3 times, it disappears.
=> Adding platform scripts

Assets/BeardAttacks.cs, Assets/Characters/Player.meta, Assets/PlayerState.cs, Assets/scene1.unity
The when the player grows/shrinks the beard health is also updated; moved beard length state and stuff to PlayerState so it's more encapsulated
=> Health vs length mechanic

Assets/Characters/Player.meta, Assets/Level 1.unity, Assets/MovementController.cs
I made beardman taller and now he can jump higher. The environment team will be working on making this level more playable this week
=> updated beardman in the level 1 scene

Assets/BossLevel.unity, Assets/BossLevel.unity.meta, Assets/Level 1.unity
First Level can be played without grapping.
=> FirstLevelTune

Assets/Beard Tip.prefab, Assets/Beard Tip.prefab.meta, Assets/BeardAnimationController.cs, Assets/BeardCollisionBehavior.cs, Assets/BeardCollisionBehavior.cs.meta, Assets/Characters/Enemies.meta, Assets/Characters/Enemies/Test Enemy.prefab, Assets/Characters/Enemies/Test Enemy.prefab.meta, Assets/Characters/Player.meta, Assets/Enemy.cs, Assets/Level 1.unity, Assets/MovementController.cs, Assets/test_beard_segment.prefab
The beard now has a collider that calls a takeDamage function on enemies
=> Player attack enemies

Assets/Characters/Player.meta, Assets/FootController.cs, Assets/FootController.cs.meta, Assets/Level 1.unity, Assets/MovementController.cs
in addition to modifying the colliders for the player's feet, I added raycasts down and to the sides to help determine if the player is grounded.
=> missing movement input bug *should* be fixed now

Assets/EnemyScripts/MovementController.cs, Assets/Level 1.unity, Assets/Texture/Charater.meta, Assets/Texture/Charater/BeardManIDle.anim, Assets/Texture/Charater/BeardManIDle.anim.meta, Assets/Texture/Charater/BeardmanSprite.controller, Assets/Texture/Charater/BeardmanSprite.controller.meta, Assets/Texture/Charater/Player_BeardManIdle_Sprite.png, Assets/Texture/Charater/Player_BeardManIdle_Sprite.png.meta, Assets/Texture/Charater/Player_BeardMan_Run_Sprite.png, Assets/Texture/Charater/Player_BeardMan_Run_Sprite.png.meta, Assets/Texture/Charater/Player_run.anim, Assets/Texture/Charater/Player_run.anim.meta
Updated movement script to update variables of animator.
Sprties added.
However moving backward need to be impolemented.
=> Character animator done

Assets/BeardAnimationController.cs, Assets/BeardController.cs
Beard once again grows and shrinks, beard segments for animation fully extend.
=> Fixed Beard Issues

Assets/BeardAttacks.cs, Assets/BeardController.cs, Assets/EnemyScripts/MovementController.cs, Assets/Level 1.unity, Assets/test_particle.prefab
Player now changes what direction their facing based on movement.  Shield with placeholder sprite implemented (Doesn't do anything atm, but has a boolean for when the player should be invincible.  Also fixed the problem with the aiming particle not being visible.
=> Shield Plus Other Fixes

Assets/DisappearingPlatform.cs, Assets/EnemyScripts/MovingPlatform.cs, Assets/Level 1.unity
disappearing platform now shakes when you land on it, and moving platform can now move left and right
=> updated moving paltform and disappearing platform

Assets/Characters/Art/SquirrelEnemy.controller, Assets/Characters/Art/SquirrelEnemy.controller.meta, Assets/Characters/Art/Squirrel_Death.anim, Assets/Characters/Art/Squirrel_Death.anim.meta, Assets/Characters/Art/Squirrel_Run.anim, Assets/Characters/Art/Squirrel_Run.anim.meta, Assets/Characters/Enemies/SquirrelEnemy.prefab, Assets/EnemyScripts/Damagable.cs, Assets/EnemyScripts/DoesDamage.cs, Assets/EnemyScripts/Movement/AnimalMovement.cs, Assets/Level1_Update.unity, Assets/PlayerState.cs
Adds animations and the necessary additions to the scripts for enemy animations to work properly.
=> Enemy art animations

Assets/BossLevel.unity, Assets/Environment/color layout_rough_boss_noplatform.png, Assets/Environment/color layout_rough_boss_noplatform.png.meta, Assets/LeadUpToBoss.unity, Assets/LeadUpToBoss.unity.meta, Assets/UI/UI Script/SceneController.cs, ProjectSettings/EditorBuildSettings.asset
added boss level scene and lead-up-to-boss scene
=> Implement boss level

Assets/Environment/DisappearingPlatform.cs
Now, player will not be able to stand on platform after it disappears
=> fixed issue with disappearing platform

Assets/Beardman Menu.unity, Assets/BossLevel.unity, Assets/LeadUpToBoss.unity, Assets/Level1_Update.unity, Assets/Scenes.meta, Assets/UI/CanvasWithSettings.prefab, Assets/UI/CanvasWithSettings.prefab.meta, Assets/UI/UI Script/EndApplication.cs, Assets/UI/UI Script/EndApplication.cs.meta, Assets/UI/UI Script/SceneController.cs, Assets/UI/UI Script/SliderState.cs
In game settings button now does opens a popup
Can now quit game from this pop up
Added an end-application button for main menu 
Added instructions for the game
=> Add more ui functionality

Assets/BossLevel.unity, Assets/Enemies/EnemyScripts/Damagable.cs, Assets/LeadUpToBoss.unity, Assets/Player/HealthConsumable.cs, Assets/Player/HealthPickUp.prefab, Assets/Player/HealthPickUp.prefab.meta, Assets/Player/HealthPickUpPhysics.physicsMaterial2D, Assets/Player/HealthPickUpPhysics.physicsMaterial2D.meta, Assets/Player/healthHeart.png, Assets/Player/healthHeart.png.meta, Assets/Resources/Player.meta, Assets/Resources/Player/HealthPickUp.prefab, Assets/Resources/Player/HealthPickUp.prefab.meta, Assets/UI/Canvas3.prefab, Assets/UI/Canvas3.prefab.meta, Assets/UI/Canvas4.prefab, Assets/UI/Canvas4.prefab.meta, Assets/UI/UI Script/SliderState.cs
anchored the in-game canvas and now enemies drop a health pick up
=> Ui and power ups

Assets/Environment/EnvironmentScripts/MovementController.cs
Character now remains crouched automatically while underneath an object.
=> Crouch Fix

Assets/BossLevel.unity
Note that the camera still needs to be fixed, and since the beard follows the mouse's position relative to the center of the screen. With no camera change, it doesn't appear to work, but a fix for the camera should correct that as well.
=> Fixed references for Beardman

Assets/Enemies/EnemyScripts/Movement/AnimalMovement.cs, ProjectSettings/InputManager.asset
Jump mapped to spacebar and w
Enemies using AnimalMovement now change direction after hitting one another.
=> Jump mapping, animal collisions

Assets/Beardman Menu.unity, Assets/BossLevel.unity, Assets/Enemies/EnemyScripts/Damagable.cs, Assets/LeadUpToBoss.unity, Assets/Player/Player Script/PlayerState.cs, Assets/Resources/Player/HealthPickUp 1.prefab, Assets/UI/Canvas8.prefab, Assets/UI/Canvas8.prefab.meta
=> updated sounds and UI

Assets/BossLevel.unity, Assets/LeadUpToBoss.unity, Assets/Player/Player Script/PlayerState.cs, Assets/Resources/Player/HealthPickUp 1.prefab, Assets/UI/Beard bar segment.png, Assets/UI/Beard bar segment.png.meta, Assets/UI/Beard bar segment.prefab, Assets/UI/Beard bar segment.prefab.meta, Assets/UI/Canvas.prefab, Assets/UI/Health bar asset-10.png, Assets/UI/Health bar asset-10.png.meta, Assets/UI/Health bar background.png, Assets/UI/Health bar background.png.meta, Assets/UI/Health bar segment.png, Assets/UI/Health bar segment.png.meta, Assets/UI/Health bar segment.prefab, Assets/UI/Health bar segment.prefab.meta, Assets/UI/UI Script/SliderState.cs
new health bar is fully functional, health is discretized now and pressing grow or shrink will do it once but again at evenly-timed intervals if held down.
=> New health bar

Assets/Player/Player Script/PlayerState.cs
healthbar now centered and max vitality (health + beard length)
=> Healthbar edits

Assets/Player/Player Script/BeardController.cs
Minimum beard length slightly increased.  Added minimum grapple force to ensure playability of boss level at lowest grapple length.
=> Bigger Minimum Grapple

Assets/Environment/EnvironmentScripts/MovementController.cs
Fixed bug where player could uncrouch in boss level.
=> Impoved detection for character crouching

Assets/Enemies/Art/StraightEdge/razor_attack.anim, Assets/Enemies/Art/StraightEdge/razor_attack.anim.meta, Assets/Enemies/Art/StraightEdge/razor_controller.controller, Assets/Enemies/Art/StraightEdge/razor_controller.controller.meta, Assets/Enemies/Art/StraightEdge/razor_move.anim, Assets/Enemies/Art/StraightEdge/razor_move.anim.meta, Assets/Enemies/EnemyScripts/Movement/StraightEdgeMovement.cs, Assets/Enemies/StraightEdgeEnemy.prefab
Signed-off-by: Steven Xie <stevengxie@gmail.com>
=> Changed StraightEdge to utilize some appropriate sprites and animations
